/**
 * Package Import
 */
import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
// Types
import type { NextPage } from 'next';

/**
 * Page
 */
const Home: NextPage = () => {
  /**
   * State
   */
  const [theme, setTheme] = useState('theme_1');

  /**
   * LifeCycles
   */
  useEffect(() => {
    if (theme) {
      document.body.className = theme;
    }
  }, [theme]);

  /**
   * Render
   */
  return (
    <div className="container mx-auto h-screen w-screen p-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <fieldset>
        <legend>Contraste</legend>
        <div className="flex flex-col">
          <label htmlFor="theme_1">
            <input
              type="radio"
              id="theme_1"
              name="theme"
              checked={theme === 'theme_1'}
              value="theme_1"
              onChange={(event: React.ChangeEvent<HTMLInputElement>) =>
                setTheme(event.target.value)
              }
            />
            theme_1
          </label>
          <label htmlFor="theme_2">
            <input
              type="radio"
              id="theme_2"
              name="theme"
              checked={theme === 'theme_2'}
              value="theme_2"
              onChange={(event: React.ChangeEvent<HTMLInputElement>) =>
                setTheme(event.target.value)
              }
            />
            theme_2
          </label>
          <label htmlFor="theme_3">
            <input
              type="radio"
              id="theme_3"
              name="theme"
              checked={theme === 'theme_3'}
              value="theme_3"
              onChange={(event: React.ChangeEvent<HTMLInputElement>) =>
                setTheme(event.target.value)
              }
            />
            theme_3
          </label>
        </div>
      </fieldset>

      <div className="container my-24 px-6 mx-auto">

  <section className="mb-32 text-gray-800">
    <div className="block rounded-lg shadow-lg bg-white">
      <div className="flex flex-wrap items-center">
        <div className="grow-0 shrink-0 basis-auto block w-full lg:flex lg:w-6/12 xl:w-4/12">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" alt="Trendy Pants and Shoes"
            className="w-full rounded-t-lg lg:rounded-tr-none lg:rounded-bl-lg" />
        </div>
        <div className="grow-0 shrink-0 basis-auto w-full lg:w-6/12 xl:w-8/12">
          <div className="px-6 py-12 md:px-12">
            <h2 className="text-3xl text-black font-bold mb-6 pb-2">One-time payment</h2>
            <p className="text-black mb-6 pb-2">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. A soluta corporis
              voluptate ab error quam dolores doloremque, quae consectetur. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates illum eos repudiandae quibusdam ratione impedit consequatur alias reprehenderit animi est et repellat voluptatem sunt, placeat iusto ipsa non a nobis.
            </p>
            <div className="flex flex-wrap mb-6">
              <div className="w-full lg:w-6/12 xl:w-4/12 mb-4">
                <p className="flex items-center text-success hover:text-success-hover hover:cursor-pointer">
                  <svg className="w-4 h-4 mr-2" role="img" xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 512 512">
                    <path fill="currentColor"
                      d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z">
                    </path>
                  </svg>Support 24/7
                </p>
              </div>
              <div className="w-full lg:w-6/12 xl:w-4/12 mb-4">
                <p className="flex items-center text-primary hover:text-primary-hover hover:cursor-pointer">
                  <svg className="w-4 h-4 mr-2" role="img" xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 512 512">
                    <path fill="currentColor"
                      d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z">
                    </path>
                  </svg>Analytics
                </p>
              </div>
              <div className="w-full lg:w-6/12 xl:w-4/12 mb-4">
                <p className="flex items-center text-info hover:text-info-hover hover:cursor-pointer">
                  <svg className="w-4 h-4 mr-2" role="img" xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 512 512">
                    <path fill="currentColor"
                      d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z">
                    </path>
                  </svg>Components
                </p>
              </div>
              <div className="w-full lg:w-6/12 xl:w-4/12 mb-4">
                <p className="flex items-center text-danger hover:text-danger-hover hover:cursor-pointer">
                  <svg className="w-4 h-4 mr-2" role="img" xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 512 512">
                    <path fill="currentColor"
                      d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z">
                    </path>
                  </svg>Updates
                </p>
              </div>
              <div className="w-full lg:w-6/12 xl:w-4/12 mb-4">
                <p className="flex items-center text-warning hover:text-warning-hover hover:cursor-pointer">
                  <svg className="w-4 h-4 mr-2" role="img" xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 512 512">
                    <path fill="currentColor"
                      d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z">
                    </path>
                  </svg>Reports
                </p>
              </div>
              <div className="w-full lg:w-6/12 xl:w-4/12 mb-4">
                <p className="flex items-center text-success hover:text-success-hover hover:cursor-pointer">
                  <svg className="w-4 h-4 mr-2" role="img" xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 512 512">
                    <path fill="currentColor"
                      d="M504 256c0 136.967-111.033 248-248 248S8 392.967 8 256 119.033 8 256 8s248 111.033 248 248zM227.314 387.314l184-184c6.248-6.248 6.248-16.379 0-22.627l-22.627-22.627c-6.248-6.249-16.379-6.249-22.628 0L216 308.118l-70.059-70.059c-6.248-6.248-16.379-6.248-22.628 0l-22.627 22.627c-6.248 6.248-6.248 16.379 0 22.627l104 104c6.249 6.249 16.379 6.249 22.628.001z">
                    </path>
                  </svg>Mobile
                </p>
              </div>
            </div>
            <button type="button"
              className="inline-block px-7 py-3 bg-primary text-white font-medium text-sm leading-snug uppercase rounded shadow-md hover:bg-primary-hover hover:shadow-lg focus:bg-primary-hover focus:shadow-lg focus:outline-none focus:ring-0 active:bg-primary-hover active:shadow-lg transition duration-150 ease-in-out"
              data-mdb-ripple="true" data-mdb-ripple-color="light">
              Buy now
            </button>
          </div>
        </div>
      </div>
    </div>
  </section>

</div>
    </div>
  );
};

export default Home;
